name: Frontend Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # paths:
    #   - 'starter/frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/setup-node

    - name: Run linting
      run: |
        cd starter/frontend
        npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/setup-node

    - name: Run tests
      run: |
        cd starter/frontend
        npm run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/setup-node

    - name: Docker build and run
      run: |
        cd starter/frontend
        docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
        docker run --name mp-frontend -p 3000:3000 -d mp-frontend